import crypto from "node:crypto";import fs from "node:fs";
const feed="https://news.google.com/rss/search?q=%22Esther%20Llamazares%22%20after%3A2025-12-31&hl=es&gl=ES&ceid=ES%3Aes",repo=process.env.GITHUB_REPOSITORY,token=process.env.GITHUB_TOKEN,dry=process.env.DRY_RUN==="1";
const dec=(v="")=>v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]+>/g," ").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&amp;/g,"&").replace(/\s+/g," ").trim(),pick=(x,t)=>dec((x.match(new RegExp("<"+t+"(?:\\s[^>]*)?>([\\s\\S]*?)<\\/"+t+">","i"))||[])[1]||""),hash=v=>crypto.createHash("sha256").update(v).digest("hex").slice(0,16);
const r=await fetch(feed);if(!r.ok)throw Error("Google News: "+r.status);const xml=await r.text();
const candidates=[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>{const x=m[1],titular=pick(x,"title"),url=pick(x,"link"),medio=pick(x,"source")||"Medio",d=new Date(pick(x,"pubDate"));return{id:"auto-"+hash(url||titular),medio,fecha:isNaN(d)?"Fecha no disponible":new Intl.DateTimeFormat("es-ES",{day:"numeric",month:"long",year:"numeric"}).format(d),publishedAt:isNaN(d)?"":d.toISOString(),titular,resumen:"Noticia publicada por "+medio+" sobre Esther Llamazares.",imagen:"/images/about.jpg",url};}).filter(x=>/esther\s+llamazares/i.test(x.titular)&&/^https:\/\//.test(x.url));
const saved=JSON.parse(fs.readFileSync(new URL("../data/press-auto.json",import.meta.url),"utf8")),known=new Set(saved.map(x=>x.id));
async function api(p,o={}){const z=await fetch("https://api.github.com"+p,{...o,headers:{accept:"application/vnd.github+json",authorization:"Bearer "+token,"user-agent":"press-monitor",...o.headers}});if(!z.ok)throw Error("GitHub "+z.status+": "+await z.text());return z.status===204?null:z.json();}
if(!dry){if(!repo||!token)throw Error("Faltan credenciales");for(const l of [{name:"prensa-pendiente",color:"D4A72C"},{name:"prensa-aprobada",color:"1F883D"},{name:"prensa-publicada",color:"0969DA"}]){const c=await fetch("https://api.github.com/repos/"+repo+"/labels/"+l.name,{headers:{authorization:"Bearer "+token}});if(c.status===404)await api("/repos/"+repo+"/labels",{method:"POST",body:JSON.stringify(l)});}for(const i of await api("/repos/"+repo+"/issues?state=all&labels=prensa-pendiente&per_page=100")){const id=i.body?.match(/<!-- press-id:([^ ]+) -->/)?.[1];if(id)known.add(id);}}
const fresh=candidates.filter(x=>!known.has(x.id)).slice(0,Number(process.env.MAX_NEW||5));
if(dry)console.log(JSON.stringify(fresh,null,2));else for(const item of fresh){const payload=Buffer.from(JSON.stringify(item)).toString("base64"),body="## Noticia encontrada\n\n**Medio:** "+item.medio+"\n\n**Fecha:** "+item.fecha+"\n\n**Titular:** "+item.titular+"\n\n**Enlace:** "+item.url+"\n\nAñade la etiqueta **prensa-aprobada** para publicarla. Para rechazarla, cierra esta propuesta.\n\n<!-- press-id:"+item.id+" -->\n<!-- press-candidate:"+payload+" -->";await api("/repos/"+repo+"/issues",{method:"POST",body:JSON.stringify({title:"[Prensa] "+item.titular.slice(0,180),body,labels:["prensa-pendiente"]})});}console.log("Propuestas nuevas: "+fresh.length);